name: "build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  tcpdog:
    name: Test and build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build client
        run: |
          cd tcpdog
          go build

      - name: Build server
        run: |
          cd server
          go build

      - name: Test
        run: go test . -timeout 5m -coverprofile=profile.cov

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
